/*
GitBook API

The GitBook API

API version: 0.0.1-beta
Contact: support@gitbook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
)

// checks if the InstallIntegrationOnSpaceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstallIntegrationOnSpaceRequest{}

// InstallIntegrationOnSpaceRequest struct for InstallIntegrationOnSpaceRequest
type InstallIntegrationOnSpaceRequest struct {
	// ID of the space to install the integration on
	Space string `json:"space"`
}

// NewInstallIntegrationOnSpaceRequest instantiates a new InstallIntegrationOnSpaceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstallIntegrationOnSpaceRequest(space string) *InstallIntegrationOnSpaceRequest {
	this := InstallIntegrationOnSpaceRequest{}
	this.Space = space
	return &this
}

// NewInstallIntegrationOnSpaceRequestWithDefaults instantiates a new InstallIntegrationOnSpaceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstallIntegrationOnSpaceRequestWithDefaults() *InstallIntegrationOnSpaceRequest {
	this := InstallIntegrationOnSpaceRequest{}
	return &this
}

// GetSpace returns the Space field value
func (o *InstallIntegrationOnSpaceRequest) GetSpace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Space
}

// GetSpaceOk returns a tuple with the Space field value
// and a boolean to check if the value has been set.
func (o *InstallIntegrationOnSpaceRequest) GetSpaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Space, true
}

// SetSpace sets field value
func (o *InstallIntegrationOnSpaceRequest) SetSpace(v string) {
	o.Space = v
}

func (o InstallIntegrationOnSpaceRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstallIntegrationOnSpaceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["space"] = o.Space
	return toSerialize, nil
}

type NullableInstallIntegrationOnSpaceRequest struct {
	value *InstallIntegrationOnSpaceRequest
	isSet bool
}

func (v NullableInstallIntegrationOnSpaceRequest) Get() *InstallIntegrationOnSpaceRequest {
	return v.value
}

func (v *NullableInstallIntegrationOnSpaceRequest) Set(val *InstallIntegrationOnSpaceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInstallIntegrationOnSpaceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInstallIntegrationOnSpaceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstallIntegrationOnSpaceRequest(val *InstallIntegrationOnSpaceRequest) *NullableInstallIntegrationOnSpaceRequest {
	return &NullableInstallIntegrationOnSpaceRequest{value: val, isSet: true}
}

func (v NullableInstallIntegrationOnSpaceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstallIntegrationOnSpaceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
