/*
GitBook API

The GitBook API

API version: 0.0.1-beta
Contact: support@gitbook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
)

// checks if the HiveAccessToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HiveAccessToken{}

// HiveAccessToken JWT tokens to authenticate in Hive for all content.
type HiveAccessToken struct {
	Contents map[string]string `json:"contents"`
}

// NewHiveAccessToken instantiates a new HiveAccessToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHiveAccessToken(contents map[string]string) *HiveAccessToken {
	this := HiveAccessToken{}
	this.Contents = contents
	return &this
}

// NewHiveAccessTokenWithDefaults instantiates a new HiveAccessToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHiveAccessTokenWithDefaults() *HiveAccessToken {
	this := HiveAccessToken{}
	return &this
}

// GetContents returns the Contents field value
func (o *HiveAccessToken) GetContents() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Contents
}

// GetContentsOk returns a tuple with the Contents field value
// and a boolean to check if the value has been set.
func (o *HiveAccessToken) GetContentsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Contents, true
}

// SetContents sets field value
func (o *HiveAccessToken) SetContents(v map[string]string) {
	o.Contents = v
}

func (o HiveAccessToken) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HiveAccessToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contents"] = o.Contents
	return toSerialize, nil
}

type NullableHiveAccessToken struct {
	value *HiveAccessToken
	isSet bool
}

func (v NullableHiveAccessToken) Get() *HiveAccessToken {
	return v.value
}

func (v *NullableHiveAccessToken) Set(val *HiveAccessToken) {
	v.value = val
	v.isSet = true
}

func (v NullableHiveAccessToken) IsSet() bool {
	return v.isSet
}

func (v *NullableHiveAccessToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHiveAccessToken(val *HiveAccessToken) *NullableHiveAccessToken {
	return &NullableHiveAccessToken{value: val, isSet: true}
}

func (v NullableHiveAccessToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHiveAccessToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
