// Copyright 2023 GitBook, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
	"fmt"
)

// ContentKitRadioValue - Value to store in th state when the checkbox is selected.
type ContentKitRadioValue struct {
	Float32 *float32
	String  *string
}

// float32AsContentKitRadioValue is a convenience function that returns float32 wrapped in ContentKitRadioValue
func Float32AsContentKitRadioValue(v *float32) ContentKitRadioValue {
	return ContentKitRadioValue{
		Float32: v,
	}
}

// stringAsContentKitRadioValue is a convenience function that returns string wrapped in ContentKitRadioValue
func StringAsContentKitRadioValue(v *string) ContentKitRadioValue {
	return ContentKitRadioValue{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ContentKitRadioValue) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Float32
	err = newStrictDecoder(data).Decode(&dst.Float32)
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			match++
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Float32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ContentKitRadioValue)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ContentKitRadioValue)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ContentKitRadioValue) MarshalJSON() ([]byte, error) {
	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ContentKitRadioValue) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.Float32 != nil {
		return obj.Float32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableContentKitRadioValue struct {
	value *ContentKitRadioValue
	isSet bool
}

func (v NullableContentKitRadioValue) Get() *ContentKitRadioValue {
	return v.value
}

func (v *NullableContentKitRadioValue) Set(val *ContentKitRadioValue) {
	v.value = val
	v.isSet = true
}

func (v NullableContentKitRadioValue) IsSet() bool {
	return v.isSet
}

func (v *NullableContentKitRadioValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentKitRadioValue(val *ContentKitRadioValue) *NullableContentKitRadioValue {
	return &NullableContentKitRadioValue{value: val, isSet: true}
}

func (v NullableContentKitRadioValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentKitRadioValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
