/*
GitBook API

The GitBook API

API version: 0.0.1-beta
Contact: support@gitbook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
	"fmt"
)

// ContentKitCardIcon - struct for ContentKitCardIcon
type ContentKitCardIcon struct {
	ContentKitIcon  *ContentKitIcon
	ContentKitImage *ContentKitImage
}

// ContentKitIconAsContentKitCardIcon is a convenience function that returns ContentKitIcon wrapped in ContentKitCardIcon
func ContentKitIconAsContentKitCardIcon(v *ContentKitIcon) ContentKitCardIcon {
	return ContentKitCardIcon{
		ContentKitIcon: v,
	}
}

// ContentKitImageAsContentKitCardIcon is a convenience function that returns ContentKitImage wrapped in ContentKitCardIcon
func ContentKitImageAsContentKitCardIcon(v *ContentKitImage) ContentKitCardIcon {
	return ContentKitCardIcon{
		ContentKitImage: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ContentKitCardIcon) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ContentKitIcon
	err = newStrictDecoder(data).Decode(&dst.ContentKitIcon)
	if err == nil {
		jsonContentKitIcon, _ := json.Marshal(dst.ContentKitIcon)
		if string(jsonContentKitIcon) == "{}" { // empty struct
			dst.ContentKitIcon = nil
		} else {
			match++
		}
	} else {
		dst.ContentKitIcon = nil
	}

	// try to unmarshal data into ContentKitImage
	err = newStrictDecoder(data).Decode(&dst.ContentKitImage)
	if err == nil {
		jsonContentKitImage, _ := json.Marshal(dst.ContentKitImage)
		if string(jsonContentKitImage) == "{}" { // empty struct
			dst.ContentKitImage = nil
		} else {
			match++
		}
	} else {
		dst.ContentKitImage = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ContentKitIcon = nil
		dst.ContentKitImage = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ContentKitCardIcon)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ContentKitCardIcon)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ContentKitCardIcon) MarshalJSON() ([]byte, error) {
	if src.ContentKitIcon != nil {
		return json.Marshal(&src.ContentKitIcon)
	}

	if src.ContentKitImage != nil {
		return json.Marshal(&src.ContentKitImage)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ContentKitCardIcon) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ContentKitIcon != nil {
		return obj.ContentKitIcon
	}

	if obj.ContentKitImage != nil {
		return obj.ContentKitImage
	}

	// all schemas are nil
	return nil
}

type NullableContentKitCardIcon struct {
	value *ContentKitCardIcon
	isSet bool
}

func (v NullableContentKitCardIcon) Get() *ContentKitCardIcon {
	return v.value
}

func (v *NullableContentKitCardIcon) Set(val *ContentKitCardIcon) {
	v.value = val
	v.isSet = true
}

func (v NullableContentKitCardIcon) IsSet() bool {
	return v.isSet
}

func (v *NullableContentKitCardIcon) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentKitCardIcon(val *ContentKitCardIcon) *NullableContentKitCardIcon {
	return &NullableContentKitCardIcon{value: val, isSet: true}
}

func (v NullableContentKitCardIcon) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentKitCardIcon) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
