/*
GitBook API

The GitBook API

API version: 0.0.1-beta
Contact: support@gitbook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
	"fmt"
)

// GetPageByPath200Response - struct for GetPageByPath200Response
type GetPageByPath200Response struct {
	RevisionPageDocument *RevisionPageDocument
	RevisionPageGroup    *RevisionPageGroup
}

// RevisionPageDocumentAsGetPageByPath200Response is a convenience function that returns RevisionPageDocument wrapped in GetPageByPath200Response
func RevisionPageDocumentAsGetPageByPath200Response(v *RevisionPageDocument) GetPageByPath200Response {
	return GetPageByPath200Response{
		RevisionPageDocument: v,
	}
}

// RevisionPageGroupAsGetPageByPath200Response is a convenience function that returns RevisionPageGroup wrapped in GetPageByPath200Response
func RevisionPageGroupAsGetPageByPath200Response(v *RevisionPageGroup) GetPageByPath200Response {
	return GetPageByPath200Response{
		RevisionPageGroup: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetPageByPath200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into RevisionPageDocument
	err = newStrictDecoder(data).Decode(&dst.RevisionPageDocument)
	if err == nil {
		jsonRevisionPageDocument, _ := json.Marshal(dst.RevisionPageDocument)
		if string(jsonRevisionPageDocument) == "{}" { // empty struct
			dst.RevisionPageDocument = nil
		} else {
			match++
		}
	} else {
		dst.RevisionPageDocument = nil
	}

	// try to unmarshal data into RevisionPageGroup
	err = newStrictDecoder(data).Decode(&dst.RevisionPageGroup)
	if err == nil {
		jsonRevisionPageGroup, _ := json.Marshal(dst.RevisionPageGroup)
		if string(jsonRevisionPageGroup) == "{}" { // empty struct
			dst.RevisionPageGroup = nil
		} else {
			match++
		}
	} else {
		dst.RevisionPageGroup = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.RevisionPageDocument = nil
		dst.RevisionPageGroup = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetPageByPath200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetPageByPath200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetPageByPath200Response) MarshalJSON() ([]byte, error) {
	if src.RevisionPageDocument != nil {
		return json.Marshal(&src.RevisionPageDocument)
	}

	if src.RevisionPageGroup != nil {
		return json.Marshal(&src.RevisionPageGroup)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetPageByPath200Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.RevisionPageDocument != nil {
		return obj.RevisionPageDocument
	}

	if obj.RevisionPageGroup != nil {
		return obj.RevisionPageGroup
	}

	// all schemas are nil
	return nil
}

type NullableGetPageByPath200Response struct {
	value *GetPageByPath200Response
	isSet bool
}

func (v NullableGetPageByPath200Response) Get() *GetPageByPath200Response {
	return v.value
}

func (v *NullableGetPageByPath200Response) Set(val *GetPageByPath200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPageByPath200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPageByPath200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPageByPath200Response(val *GetPageByPath200Response) *NullableGetPageByPath200Response {
	return &NullableGetPageByPath200Response{value: val, isSet: true}
}

func (v NullableGetPageByPath200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPageByPath200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
