/*
GitBook API

The GitBook API

API version: 0.0.1-beta
Contact: support@gitbook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
)

// checks if the ListSpacesForOrganizationMember200ResponseAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSpacesForOrganizationMember200ResponseAllOf{}

// ListSpacesForOrganizationMember200ResponseAllOf struct for ListSpacesForOrganizationMember200ResponseAllOf
type ListSpacesForOrganizationMember200ResponseAllOf struct {
	Items []MemberContentPermission `json:"items"`
}

// NewListSpacesForOrganizationMember200ResponseAllOf instantiates a new ListSpacesForOrganizationMember200ResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSpacesForOrganizationMember200ResponseAllOf(items []MemberContentPermission) *ListSpacesForOrganizationMember200ResponseAllOf {
	this := ListSpacesForOrganizationMember200ResponseAllOf{}
	this.Items = items
	return &this
}

// NewListSpacesForOrganizationMember200ResponseAllOfWithDefaults instantiates a new ListSpacesForOrganizationMember200ResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSpacesForOrganizationMember200ResponseAllOfWithDefaults() *ListSpacesForOrganizationMember200ResponseAllOf {
	this := ListSpacesForOrganizationMember200ResponseAllOf{}
	return &this
}

// GetItems returns the Items field value
func (o *ListSpacesForOrganizationMember200ResponseAllOf) GetItems() []MemberContentPermission {
	if o == nil {
		var ret []MemberContentPermission
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListSpacesForOrganizationMember200ResponseAllOf) GetItemsOk() ([]MemberContentPermission, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListSpacesForOrganizationMember200ResponseAllOf) SetItems(v []MemberContentPermission) {
	o.Items = v
}

func (o ListSpacesForOrganizationMember200ResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSpacesForOrganizationMember200ResponseAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableListSpacesForOrganizationMember200ResponseAllOf struct {
	value *ListSpacesForOrganizationMember200ResponseAllOf
	isSet bool
}

func (v NullableListSpacesForOrganizationMember200ResponseAllOf) Get() *ListSpacesForOrganizationMember200ResponseAllOf {
	return v.value
}

func (v *NullableListSpacesForOrganizationMember200ResponseAllOf) Set(val *ListSpacesForOrganizationMember200ResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableListSpacesForOrganizationMember200ResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableListSpacesForOrganizationMember200ResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSpacesForOrganizationMember200ResponseAllOf(val *ListSpacesForOrganizationMember200ResponseAllOf) *NullableListSpacesForOrganizationMember200ResponseAllOf {
	return &NullableListSpacesForOrganizationMember200ResponseAllOf{value: val, isSet: true}
}

func (v NullableListSpacesForOrganizationMember200ResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSpacesForOrganizationMember200ResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
