/*
GitBook API

The GitBook API

API version: 0.0.1-beta
Contact: support@gitbook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
)

// checks if the CustomFieldUrls type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomFieldUrls{}

// CustomFieldUrls URLs associated with the object
type CustomFieldUrls struct {
	// URL of the custom field in the API
	Location string `json:"location"`
}

// NewCustomFieldUrls instantiates a new CustomFieldUrls object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomFieldUrls(location string) *CustomFieldUrls {
	this := CustomFieldUrls{}
	this.Location = location
	return &this
}

// NewCustomFieldUrlsWithDefaults instantiates a new CustomFieldUrls object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomFieldUrlsWithDefaults() *CustomFieldUrls {
	this := CustomFieldUrls{}
	return &this
}

// GetLocation returns the Location field value
func (o *CustomFieldUrls) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *CustomFieldUrls) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *CustomFieldUrls) SetLocation(v string) {
	o.Location = v
}

func (o CustomFieldUrls) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomFieldUrls) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["location"] = o.Location
	return toSerialize, nil
}

type NullableCustomFieldUrls struct {
	value *CustomFieldUrls
	isSet bool
}

func (v NullableCustomFieldUrls) Get() *CustomFieldUrls {
	return v.value
}

func (v *NullableCustomFieldUrls) Set(val *CustomFieldUrls) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomFieldUrls) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomFieldUrls) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomFieldUrls(val *CustomFieldUrls) *NullableCustomFieldUrls {
	return &NullableCustomFieldUrls{value: val, isSet: true}
}

func (v NullableCustomFieldUrls) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomFieldUrls) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
