/*
Copyright 2023 GitBook, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
	"fmt"
)

// ContentKitLinkTargetUrl - struct for ContentKitLinkTargetUrl
type ContentKitLinkTargetUrl struct {
	ContentKitURL *ContentKitURL
	String        *string
}

// ContentKitURLAsContentKitLinkTargetUrl is a convenience function that returns ContentKitURL wrapped in ContentKitLinkTargetUrl
func ContentKitURLAsContentKitLinkTargetUrl(v *ContentKitURL) ContentKitLinkTargetUrl {
	return ContentKitLinkTargetUrl{
		ContentKitURL: v,
	}
}

// stringAsContentKitLinkTargetUrl is a convenience function that returns string wrapped in ContentKitLinkTargetUrl
func StringAsContentKitLinkTargetUrl(v *string) ContentKitLinkTargetUrl {
	return ContentKitLinkTargetUrl{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *ContentKitLinkTargetUrl) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ContentKitURL
	err = newStrictDecoder(data).Decode(&dst.ContentKitURL)
	if err == nil {
		jsonContentKitURL, _ := json.Marshal(dst.ContentKitURL)
		if string(jsonContentKitURL) == "{}" { // empty struct
			dst.ContentKitURL = nil
		} else {
			match++
		}
	} else {
		dst.ContentKitURL = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ContentKitURL = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ContentKitLinkTargetUrl)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ContentKitLinkTargetUrl)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ContentKitLinkTargetUrl) MarshalJSON() ([]byte, error) {
	if src.ContentKitURL != nil {
		return json.Marshal(&src.ContentKitURL)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ContentKitLinkTargetUrl) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.ContentKitURL != nil {
		return obj.ContentKitURL
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableContentKitLinkTargetUrl struct {
	value *ContentKitLinkTargetUrl
	isSet bool
}

func (v NullableContentKitLinkTargetUrl) Get() *ContentKitLinkTargetUrl {
	return v.value
}

func (v *NullableContentKitLinkTargetUrl) Set(val *ContentKitLinkTargetUrl) {
	v.value = val
	v.isSet = true
}

func (v NullableContentKitLinkTargetUrl) IsSet() bool {
	return v.isSet
}

func (v *NullableContentKitLinkTargetUrl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentKitLinkTargetUrl(val *ContentKitLinkTargetUrl) *NullableContentKitLinkTargetUrl {
	return &NullableContentKitLinkTargetUrl{value: val, isSet: true}
}

func (v NullableContentKitLinkTargetUrl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentKitLinkTargetUrl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
