// Copyright 2023 GitBook, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
)

// checks if the OrganizationTarget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationTarget{}

// OrganizationTarget struct for OrganizationTarget
type OrganizationTarget struct {
	Organization string `json:"organization"`
}

// NewOrganizationTarget instantiates a new OrganizationTarget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationTarget(organization string) *OrganizationTarget {
	this := OrganizationTarget{}
	this.Organization = organization
	return &this
}

// NewOrganizationTargetWithDefaults instantiates a new OrganizationTarget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationTargetWithDefaults() *OrganizationTarget {
	this := OrganizationTarget{}
	return &this
}

// GetOrganization returns the Organization field value
func (o *OrganizationTarget) GetOrganization() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value
// and a boolean to check if the value has been set.
func (o *OrganizationTarget) GetOrganizationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organization, true
}

// SetOrganization sets field value
func (o *OrganizationTarget) SetOrganization(v string) {
	o.Organization = v
}

func (o OrganizationTarget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationTarget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organization"] = o.Organization
	return toSerialize, nil
}

type NullableOrganizationTarget struct {
	value *OrganizationTarget
	isSet bool
}

func (v NullableOrganizationTarget) Get() *OrganizationTarget {
	return v.value
}

func (v *NullableOrganizationTarget) Set(val *OrganizationTarget) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationTarget) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationTarget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationTarget(val *OrganizationTarget) *NullableOrganizationTarget {
	return &NullableOrganizationTarget{value: val, isSet: true}
}

func (v NullableOrganizationTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationTarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
