// Copyright 2023 GitBook, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
)

// checks if the OrganizationUrls type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationUrls{}

// OrganizationUrls URLs associated with the object
type OrganizationUrls struct {
	// URL of the organization in the API
	Location string `json:"location"`
	// URL of the organization in the application
	App string `json:"app"`
}

// NewOrganizationUrls instantiates a new OrganizationUrls object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationUrls(location string, app string) *OrganizationUrls {
	this := OrganizationUrls{}
	this.Location = location
	this.App = app
	return &this
}

// NewOrganizationUrlsWithDefaults instantiates a new OrganizationUrls object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationUrlsWithDefaults() *OrganizationUrls {
	this := OrganizationUrls{}
	return &this
}

// GetLocation returns the Location field value
func (o *OrganizationUrls) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *OrganizationUrls) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *OrganizationUrls) SetLocation(v string) {
	o.Location = v
}

// GetApp returns the App field value
func (o *OrganizationUrls) GetApp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.App
}

// GetAppOk returns a tuple with the App field value
// and a boolean to check if the value has been set.
func (o *OrganizationUrls) GetAppOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.App, true
}

// SetApp sets field value
func (o *OrganizationUrls) SetApp(v string) {
	o.App = v
}

func (o OrganizationUrls) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationUrls) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["location"] = o.Location
	toSerialize["app"] = o.App
	return toSerialize, nil
}

type NullableOrganizationUrls struct {
	value *OrganizationUrls
	isSet bool
}

func (v NullableOrganizationUrls) Get() *OrganizationUrls {
	return v.value
}

func (v *NullableOrganizationUrls) Set(val *OrganizationUrls) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationUrls) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationUrls) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationUrls(val *OrganizationUrls) *NullableOrganizationUrls {
	return &NullableOrganizationUrls{value: val, isSet: true}
}

func (v NullableOrganizationUrls) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationUrls) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
