/*
GitBook API

The GitBook API

API version: 0.0.1-beta
Contact: support@gitbook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
)

// checks if the OrganizationSpacesChannel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationSpacesChannel{}

// OrganizationSpacesChannel Subscription channel for changes in spaces in an organization.
type OrganizationSpacesChannel struct {
	Channel      string `json:"channel"`
	Organization string `json:"organization"`
}

// NewOrganizationSpacesChannel instantiates a new OrganizationSpacesChannel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationSpacesChannel(channel string, organization string) *OrganizationSpacesChannel {
	this := OrganizationSpacesChannel{}
	this.Channel = channel
	this.Organization = organization
	return &this
}

// NewOrganizationSpacesChannelWithDefaults instantiates a new OrganizationSpacesChannel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationSpacesChannelWithDefaults() *OrganizationSpacesChannel {
	this := OrganizationSpacesChannel{}
	return &this
}

// GetChannel returns the Channel field value
func (o *OrganizationSpacesChannel) GetChannel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *OrganizationSpacesChannel) GetChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *OrganizationSpacesChannel) SetChannel(v string) {
	o.Channel = v
}

// GetOrganization returns the Organization field value
func (o *OrganizationSpacesChannel) GetOrganization() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value
// and a boolean to check if the value has been set.
func (o *OrganizationSpacesChannel) GetOrganizationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organization, true
}

// SetOrganization sets field value
func (o *OrganizationSpacesChannel) SetOrganization(v string) {
	o.Organization = v
}

func (o OrganizationSpacesChannel) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationSpacesChannel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channel"] = o.Channel
	toSerialize["organization"] = o.Organization
	return toSerialize, nil
}

type NullableOrganizationSpacesChannel struct {
	value *OrganizationSpacesChannel
	isSet bool
}

func (v NullableOrganizationSpacesChannel) Get() *OrganizationSpacesChannel {
	return v.value
}

func (v *NullableOrganizationSpacesChannel) Set(val *OrganizationSpacesChannel) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationSpacesChannel) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationSpacesChannel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationSpacesChannel(val *OrganizationSpacesChannel) *NullableOrganizationSpacesChannel {
	return &NullableOrganizationSpacesChannel{value: val, isSet: true}
}

func (v NullableOrganizationSpacesChannel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationSpacesChannel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
