// Copyright 2023 GitBook, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
)

// checks if the ContentKitContextConfigurationSpaceAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentKitContextConfigurationSpaceAllOf{}

// ContentKitContextConfigurationSpaceAllOf Context while rendering in a space-installation's configuration.
type ContentKitContextConfigurationSpaceAllOf struct {
	Type string `json:"type"`
	// ID of the space the space-installation configuration is in.
	SpaceId string `json:"spaceId"`
}

// NewContentKitContextConfigurationSpaceAllOf instantiates a new ContentKitContextConfigurationSpaceAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentKitContextConfigurationSpaceAllOf(type_ string, spaceId string) *ContentKitContextConfigurationSpaceAllOf {
	this := ContentKitContextConfigurationSpaceAllOf{}
	this.Type = type_
	this.SpaceId = spaceId
	return &this
}

// NewContentKitContextConfigurationSpaceAllOfWithDefaults instantiates a new ContentKitContextConfigurationSpaceAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentKitContextConfigurationSpaceAllOfWithDefaults() *ContentKitContextConfigurationSpaceAllOf {
	this := ContentKitContextConfigurationSpaceAllOf{}
	return &this
}

// GetType returns the Type field value
func (o *ContentKitContextConfigurationSpaceAllOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ContentKitContextConfigurationSpaceAllOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ContentKitContextConfigurationSpaceAllOf) SetType(v string) {
	o.Type = v
}

// GetSpaceId returns the SpaceId field value
func (o *ContentKitContextConfigurationSpaceAllOf) GetSpaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SpaceId
}

// GetSpaceIdOk returns a tuple with the SpaceId field value
// and a boolean to check if the value has been set.
func (o *ContentKitContextConfigurationSpaceAllOf) GetSpaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SpaceId, true
}

// SetSpaceId sets field value
func (o *ContentKitContextConfigurationSpaceAllOf) SetSpaceId(v string) {
	o.SpaceId = v
}

func (o ContentKitContextConfigurationSpaceAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentKitContextConfigurationSpaceAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["spaceId"] = o.SpaceId
	return toSerialize, nil
}

type NullableContentKitContextConfigurationSpaceAllOf struct {
	value *ContentKitContextConfigurationSpaceAllOf
	isSet bool
}

func (v NullableContentKitContextConfigurationSpaceAllOf) Get() *ContentKitContextConfigurationSpaceAllOf {
	return v.value
}

func (v *NullableContentKitContextConfigurationSpaceAllOf) Set(val *ContentKitContextConfigurationSpaceAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableContentKitContextConfigurationSpaceAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableContentKitContextConfigurationSpaceAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentKitContextConfigurationSpaceAllOf(val *ContentKitContextConfigurationSpaceAllOf) *NullableContentKitContextConfigurationSpaceAllOf {
	return &NullableContentKitContextConfigurationSpaceAllOf{value: val, isSet: true}
}

func (v NullableContentKitContextConfigurationSpaceAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentKitContextConfigurationSpaceAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
