/*
Copyright 2023 GitBook, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
)

// checks if the ListMembersInOrganizationById200ResponseAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMembersInOrganizationById200ResponseAllOf{}

// ListMembersInOrganizationById200ResponseAllOf struct for ListMembersInOrganizationById200ResponseAllOf
type ListMembersInOrganizationById200ResponseAllOf struct {
	Items []OrganizationMember `json:"items"`
}

// NewListMembersInOrganizationById200ResponseAllOf instantiates a new ListMembersInOrganizationById200ResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMembersInOrganizationById200ResponseAllOf(items []OrganizationMember) *ListMembersInOrganizationById200ResponseAllOf {
	this := ListMembersInOrganizationById200ResponseAllOf{}
	this.Items = items
	return &this
}

// NewListMembersInOrganizationById200ResponseAllOfWithDefaults instantiates a new ListMembersInOrganizationById200ResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMembersInOrganizationById200ResponseAllOfWithDefaults() *ListMembersInOrganizationById200ResponseAllOf {
	this := ListMembersInOrganizationById200ResponseAllOf{}
	return &this
}

// GetItems returns the Items field value
func (o *ListMembersInOrganizationById200ResponseAllOf) GetItems() []OrganizationMember {
	if o == nil {
		var ret []OrganizationMember
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListMembersInOrganizationById200ResponseAllOf) GetItemsOk() ([]OrganizationMember, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListMembersInOrganizationById200ResponseAllOf) SetItems(v []OrganizationMember) {
	o.Items = v
}

func (o ListMembersInOrganizationById200ResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMembersInOrganizationById200ResponseAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableListMembersInOrganizationById200ResponseAllOf struct {
	value *ListMembersInOrganizationById200ResponseAllOf
	isSet bool
}

func (v NullableListMembersInOrganizationById200ResponseAllOf) Get() *ListMembersInOrganizationById200ResponseAllOf {
	return v.value
}

func (v *NullableListMembersInOrganizationById200ResponseAllOf) Set(val *ListMembersInOrganizationById200ResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableListMembersInOrganizationById200ResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableListMembersInOrganizationById200ResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMembersInOrganizationById200ResponseAllOf(val *ListMembersInOrganizationById200ResponseAllOf) *NullableListMembersInOrganizationById200ResponseAllOf {
	return &NullableListMembersInOrganizationById200ResponseAllOf{value: val, isSet: true}
}

func (v NullableListMembersInOrganizationById200ResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMembersInOrganizationById200ResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
