/*
Copyright 2023 GitBook, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
)

// checks if the ContentKitDynamicBinding type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContentKitDynamicBinding{}

// ContentKitDynamicBinding Binding between a property and a state value.
type ContentKitDynamicBinding struct {
	// Key in the state
	State string `json:"$state"`
}

// NewContentKitDynamicBinding instantiates a new ContentKitDynamicBinding object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContentKitDynamicBinding(state string) *ContentKitDynamicBinding {
	this := ContentKitDynamicBinding{}
	this.State = state
	return &this
}

// NewContentKitDynamicBindingWithDefaults instantiates a new ContentKitDynamicBinding object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContentKitDynamicBindingWithDefaults() *ContentKitDynamicBinding {
	this := ContentKitDynamicBinding{}
	return &this
}

// GetState returns the State field value
func (o *ContentKitDynamicBinding) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ContentKitDynamicBinding) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ContentKitDynamicBinding) SetState(v string) {
	o.State = v
}

func (o ContentKitDynamicBinding) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContentKitDynamicBinding) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["$state"] = o.State
	return toSerialize, nil
}

type NullableContentKitDynamicBinding struct {
	value *ContentKitDynamicBinding
	isSet bool
}

func (v NullableContentKitDynamicBinding) Get() *ContentKitDynamicBinding {
	return v.value
}

func (v *NullableContentKitDynamicBinding) Set(val *ContentKitDynamicBinding) {
	v.value = val
	v.isSet = true
}

func (v NullableContentKitDynamicBinding) IsSet() bool {
	return v.isSet
}

func (v *NullableContentKitDynamicBinding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContentKitDynamicBinding(val *ContentKitDynamicBinding) *NullableContentKitDynamicBinding {
	return &NullableContentKitDynamicBinding{value: val, isSet: true}
}

func (v NullableContentKitDynamicBinding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContentKitDynamicBinding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
