/*
Copyright 2023 GitBook, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
)

// checks if the ListTeamsForOrganizationMember200ResponseAllOfItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTeamsForOrganizationMember200ResponseAllOfItemsInner{}

// ListTeamsForOrganizationMember200ResponseAllOfItemsInner struct for ListTeamsForOrganizationMember200ResponseAllOfItemsInner
type ListTeamsForOrganizationMember200ResponseAllOfItemsInner struct {
	Team   OrganizationTeam `json:"team"`
	Member TeamMember       `json:"member"`
}

// NewListTeamsForOrganizationMember200ResponseAllOfItemsInner instantiates a new ListTeamsForOrganizationMember200ResponseAllOfItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTeamsForOrganizationMember200ResponseAllOfItemsInner(team OrganizationTeam, member TeamMember) *ListTeamsForOrganizationMember200ResponseAllOfItemsInner {
	this := ListTeamsForOrganizationMember200ResponseAllOfItemsInner{}
	this.Team = team
	this.Member = member
	return &this
}

// NewListTeamsForOrganizationMember200ResponseAllOfItemsInnerWithDefaults instantiates a new ListTeamsForOrganizationMember200ResponseAllOfItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTeamsForOrganizationMember200ResponseAllOfItemsInnerWithDefaults() *ListTeamsForOrganizationMember200ResponseAllOfItemsInner {
	this := ListTeamsForOrganizationMember200ResponseAllOfItemsInner{}
	return &this
}

// GetTeam returns the Team field value
func (o *ListTeamsForOrganizationMember200ResponseAllOfItemsInner) GetTeam() OrganizationTeam {
	if o == nil {
		var ret OrganizationTeam
		return ret
	}

	return o.Team
}

// GetTeamOk returns a tuple with the Team field value
// and a boolean to check if the value has been set.
func (o *ListTeamsForOrganizationMember200ResponseAllOfItemsInner) GetTeamOk() (*OrganizationTeam, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Team, true
}

// SetTeam sets field value
func (o *ListTeamsForOrganizationMember200ResponseAllOfItemsInner) SetTeam(v OrganizationTeam) {
	o.Team = v
}

// GetMember returns the Member field value
func (o *ListTeamsForOrganizationMember200ResponseAllOfItemsInner) GetMember() TeamMember {
	if o == nil {
		var ret TeamMember
		return ret
	}

	return o.Member
}

// GetMemberOk returns a tuple with the Member field value
// and a boolean to check if the value has been set.
func (o *ListTeamsForOrganizationMember200ResponseAllOfItemsInner) GetMemberOk() (*TeamMember, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Member, true
}

// SetMember sets field value
func (o *ListTeamsForOrganizationMember200ResponseAllOfItemsInner) SetMember(v TeamMember) {
	o.Member = v
}

func (o ListTeamsForOrganizationMember200ResponseAllOfItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTeamsForOrganizationMember200ResponseAllOfItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["team"] = o.Team
	toSerialize["member"] = o.Member
	return toSerialize, nil
}

type NullableListTeamsForOrganizationMember200ResponseAllOfItemsInner struct {
	value *ListTeamsForOrganizationMember200ResponseAllOfItemsInner
	isSet bool
}

func (v NullableListTeamsForOrganizationMember200ResponseAllOfItemsInner) Get() *ListTeamsForOrganizationMember200ResponseAllOfItemsInner {
	return v.value
}

func (v *NullableListTeamsForOrganizationMember200ResponseAllOfItemsInner) Set(val *ListTeamsForOrganizationMember200ResponseAllOfItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListTeamsForOrganizationMember200ResponseAllOfItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListTeamsForOrganizationMember200ResponseAllOfItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTeamsForOrganizationMember200ResponseAllOfItemsInner(val *ListTeamsForOrganizationMember200ResponseAllOfItemsInner) *NullableListTeamsForOrganizationMember200ResponseAllOfItemsInner {
	return &NullableListTeamsForOrganizationMember200ResponseAllOfItemsInner{value: val, isSet: true}
}

func (v NullableListTeamsForOrganizationMember200ResponseAllOfItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTeamsForOrganizationMember200ResponseAllOfItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
