/*
GitBook API

The GitBook API

API version: 0.0.1-beta
Contact: support@gitbook.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gitbook

import (
	"encoding/json"
)

// checks if the ListIntegrationInstallations200ResponseAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListIntegrationInstallations200ResponseAllOf{}

// ListIntegrationInstallations200ResponseAllOf struct for ListIntegrationInstallations200ResponseAllOf
type ListIntegrationInstallations200ResponseAllOf struct {
	Items []IntegrationInstallation `json:"items"`
}

// NewListIntegrationInstallations200ResponseAllOf instantiates a new ListIntegrationInstallations200ResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListIntegrationInstallations200ResponseAllOf(items []IntegrationInstallation) *ListIntegrationInstallations200ResponseAllOf {
	this := ListIntegrationInstallations200ResponseAllOf{}
	this.Items = items
	return &this
}

// NewListIntegrationInstallations200ResponseAllOfWithDefaults instantiates a new ListIntegrationInstallations200ResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListIntegrationInstallations200ResponseAllOfWithDefaults() *ListIntegrationInstallations200ResponseAllOf {
	this := ListIntegrationInstallations200ResponseAllOf{}
	return &this
}

// GetItems returns the Items field value
func (o *ListIntegrationInstallations200ResponseAllOf) GetItems() []IntegrationInstallation {
	if o == nil {
		var ret []IntegrationInstallation
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListIntegrationInstallations200ResponseAllOf) GetItemsOk() ([]IntegrationInstallation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListIntegrationInstallations200ResponseAllOf) SetItems(v []IntegrationInstallation) {
	o.Items = v
}

func (o ListIntegrationInstallations200ResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListIntegrationInstallations200ResponseAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableListIntegrationInstallations200ResponseAllOf struct {
	value *ListIntegrationInstallations200ResponseAllOf
	isSet bool
}

func (v NullableListIntegrationInstallations200ResponseAllOf) Get() *ListIntegrationInstallations200ResponseAllOf {
	return v.value
}

func (v *NullableListIntegrationInstallations200ResponseAllOf) Set(val *ListIntegrationInstallations200ResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableListIntegrationInstallations200ResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableListIntegrationInstallations200ResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListIntegrationInstallations200ResponseAllOf(val *ListIntegrationInstallations200ResponseAllOf) *NullableListIntegrationInstallations200ResponseAllOf {
	return &NullableListIntegrationInstallations200ResponseAllOf{value: val, isSet: true}
}

func (v NullableListIntegrationInstallations200ResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListIntegrationInstallations200ResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
